In [1]:
# coding: utf-8
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [2]:
df = pd.read_csv('../data/共享单车_天气清洗后.csv')
df.head()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   日期             31 non-null     object
 1   最高温            31 non-null     object
 2   最低温            31 non-null     object
 3   天气             31 non-null     object
 4   风力风向           31 non-null     object
 5   日照时长           31 non-null     object
 6   date           31 non-null     object
 7   max_temp(℃)    31 non-null     float64
 8   min_temp(℃)    31 non-null     float64
 9   avg_temp(℃)    31 non-null     float64
 10  sunshine_h(h)  31 non-null     float64
 11  date_only      31 non-null     object
dtypes: float64(4), object(8)
memory usage: 3.0+ KB

In [5]:
df = pd.read_csv('../data/共享单车_清洗后.csv')
df.head()

,orderid,bikeid,userid,start_time,start_location_x(°),start_location_y(°),end_time,end_location_x(°),end_location_y(°),track,...,speed_kmh,time_period,is_weekend,ride_date,天气,avg_temp(℃),sunshine_h(h),max_temp(℃),min_temp(℃),actual_temp(℃)
0,78387,158357,10080,2016-08-20 06:57:00,121.35,31.39,2016-08-20 07:04:00,121.36,31.39,"121.347,31.392#121.348,31.389#121.349,31.390#1...",...,7.39,早高峰(6-9点),1,2016-08-20,晴,31.00,11.90,33.80,28.10,28.10
1,891333,92776,6605,2016-08-29 19:09:00,121.51,31.28,2016-08-29 19:31:00,121.49,31.27,"121.489,31.270#121.489,31.271#121.490,31.270#1...",...,5.49,晚高峰(17-20点),0,2016-08-29,晴,25.20,12.00,29.50,21.00,25.20
2,1106623,152045,8876,2016-08-13 16:17:00,121.38,31.25,2016-08-13 16:36:00,121.41,31.25,"121.381,31.251#121.382,31.251#121.382,31.252#1...",...,6.93,日间(9-17点),1,2016-08-13,晴,29.60,12.00,31.90,27.40,31.90
3,1389484,196259,10648,2016-08-23 21:34:00,121.48,31.32,2016-08-23 21:43:00,121.47,31.32,"121.471,31.325#121.472,31.325#121.473,31.324#1...",...,9.03,夜间(20-6点),0,2016-08-23,晴,28.90,11.90,31.60,26.20,26.20
4,188537,78208,11735,2016-08-16 07:32:00,121.41,31.29,2016-08-16 07:41:00,121.42,31.29,"121.407,31.291#121.407,31.292#121.408,31.291#1...",...,7.57,早高峰(6-9点),0,2016-08-16,晴,29.20,12.00,31.80,26.60,29.20

In [2]:
df = pd.read_csv('../data/共享单车_单车特征.csv')
df.head()

,bikeid,ride_count(次),total_distance(km),avg_distance(km),total_duration(min),avg_duration(min)
0,3,1,2.14,2.14,20.00,20.00
1,6,1,0.38,0.38,4.00,4.00
2,13,2,0.88,0.44,7.00,3.50
3,22,1,0.87,0.87,12.00,12.00
4,25,1,2.01,2.01,21.00,21.00

In [7]:
df = pd.read_csv('../data/共享单车_用户特征.csv')
df.head()

,userid,recency(day),frequency(次),total_distance(km),total_duration(min),avg_duration(min),avg_speed(km/h)
0,1,0,5,7.18,87.00,17.40,5.87
1,3,3,8,8.49,108.00,13.50,4.81
2,6,0,2,2.58,29.00,14.50,5.68
3,7,6,8,10.49,118.00,14.75,5.37
4,8,4,7,7.09,82.00,11.71,6.01