## 共享单车数据处理

### 导包

In [3]:
 # coding: utf-8
# 导入三大神器
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# 解决字体mac/win
# plt.rcParams['font.sans-serif'] = ['STHeiti']
plt.rcParams['font.sans-serif'] = ['SimHei']        # 用来正常显示中文标签（黑体）

# 解决负号显示问题
plt.rcParams['axes.unicode_minus'] = False

### 数据处理

In [5]:
df1 = pd.read_csv('../data/上海共享单车数据.csv')
#抽样 抽五条数据
df1.head()

,orderid,bikeid,userid,start_time,start_location_x,start_location_y,end_time,end_location_x,end_location_y,track
0,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,"121.347,31.392#121.348,31.389#121.349,31.390#1..."
1,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,"121.489,31.270#121.489,31.271#121.490,31.270#1..."
2,1106623,152045,8876,2016-08-13 16:17,121.383,31.254,2016-08-13 16:36,121.405,31.248,"121.381,31.251#121.382,31.251#121.382,31.252#1..."
3,1389484,196259,10648,2016-08-23 21:34,121.484,31.320,2016-08-23 21:43,121.471,31.325,"121.471,31.325#121.472,31.325#121.473,31.324#1..."
4,188537,78208,11735,2016-08-16 07:32,121.407,31.292,2016-08-16 07:41,121.418,31.288,"121.407,31.291#121.407,31.292#121.408,31.291#1..."

In [7]:
df2 = pd.read_excel('../data/上海天气.xlsx')
df2.head()

              日期    最高温    最低温   天气   风力风向    日照时长
0  2016-08-01 周一  31.8℃  27.2℃    晴  东南风3级  12.0小时
1  2016-08-02 周二  32.3℃  27.9℃  毛毛雨  东南风3级  10.5小时
2  2016-08-03 周三  28.7℃  26.1℃   中雨  西南风3级   0.4小时
3  2016-08-04 周四  31.5℃  25.2℃   中雨   北风2级  10.0小时
4  2016-08-05 周五  30.9℃    26℃  毛毛雨   北风2级   7.5小时

In [8]:
df1.info()
#需要缺失值、数据类型处理

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102361 entries, 0 to 102360
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   orderid           102361 non-null  int64
 1   bikeid            102361 non-null  int64
 2   userid            102361 non-null  int64
 3   start_time        102361 non-null  object
 4   start_location_x  102361 non-null  float64
 5   start_location_y  102361 non-null  float64
 6   end_time          102361 non-null  object
 7   end_location_x    102361 non-null  float64
 8   end_location_y    102361 non-null  float64
 9   track             102361 non-null  object
dtypes: float64(4), int64(3), object(3)
memory usage: 7.8+ MB

In [9]:
df1.describe()
#

,orderid,bikeid,userid,start_location_x,start_location_y,end_location_x,end_location_y
count,1.023610e+05,102361.000000,102361.000000,102361.000000,102361.000000,102361.000000,102361.000000
mean,8.940838e+05,155425.868690,7834.435644,121.454144,31.251740,121.453736,31.252029
std,5.219651e+05,98816.625402,4530.387938,0.060862,0.057358,0.061577,0.057740
min,6.000000e+00,3.000000,1.000000,121.173000,30.842000,120.486000,30.841000
25%,4.386790e+05,74701.000000,4095.000000,121.415000,31.212000,121.414000,31.212000
50%,8.901510e+05,141990.000000,7617.000000,121.456000,31.260000,121.456000,31.261000
75%,1.343252e+06,228303.000000,11278.000000,121.497000,31.294000,121.497000,31.294000
max,1.807864e+06,387351.000000,17753.000000,121.970000,31.450000,121.971000,31.477000